version: v1.1.0
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://inifaisal.github.io"


# the subpath of your site, e.g. /blog
baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-71928912-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# Time Zone #
#############

#timezone: "+0800"

#############
# HTML Head #
#############

lang: "en"
author: "faisal"
title: "ini Faisal"
description: "Web Blognya si faisal, ngeblog tentang coding dan teknologi, catatan pelajaran otodidak tentang dunia pemrograman."
keywords: "tutorial, php, java, javascript, angularjs, reactjs, coding, teknologi, gadget, linux, ubuntu, android"
favicon: "/img/favicon.ico"


########
# Blog #
########

post-preview-words: 96

# Permalinks
permalink: /:year/:month/:title


# Pagination & path
paginate: 10
paginate_path: "blog/page:num/"


################
# Social Share #
################

fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True


##########
# Disqus #
##########

disqus-shortname: "inifaisal"

###########
# Contact #
###########

email: "inifaisal.id@gmail.com"

#########################
# Footer Social Buttons #
#########################

social:

  - title: "twitter"
    url: "https://twitter.com/faisal_ini"
  - title: "github"
    url: "https://github.com/inifaisal"
  - title: "rss"
    url: "/feed.xml"


################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Blog: 'blog'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "scripts"]

markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

# Enable minification SASS

sass:
  style: compressed

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
